---
environments:
  default:
    values:
      - environments/default/values.yaml
---

helmfiles:
  - path: git::https://github.com/mueller-tobias/helmfile-test.git@remote-helmfile/helmfile.yaml
    values:
    - {{ toYaml .Values | nindent 6 }}
