# Dummy Helmfile that shoud represent the openDesk the Deployment

bases:
  - "../../bases/environments.yaml"

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    labels:
      job: {{ .Values.nginx.service.type}}
    chart: bitnami/nginx
    values:
      - nginx.yaml.gotmpl
      - {{ toYaml .Values | nindent 6 }}
    # DB host, port, and connection opts for the environment
