# Dummy Helmfile that shoud represent the openDesk the Deployment
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami

releases:
  - name: nginx
    labels:
      job: dbmigrator
    chart: bitnami/nginx
    # DB host, port, and connection opts for the environment
    values:
    - "deploy/environments/dev/values.yaml"
