helmfiles:
- path: helmfile/apps/nginx/helmfile.yaml
  values:
  - {{ toYaml .Values | nindent 6 }}

environments:
  default:
    values:
      - "helmfile/environments/default/*.yaml"
      - {{ toYaml .Values | nindent 10 }}
